In [5]:
import cv2
import numpy as np
import glob

DICT = cv2.aruco.DICT_6X6_50           # Тип маркеров aruco
CELLS_X, CELLS_Y = 7, 10            # Размер доски (количество клеток)
CELL_WIDTH, MARKER_WIDTH = 0.04, 0.02  # Размер клетки и маркера в метрах

DICT = cv2.aruco.getPredefinedDictionary(DICT)
charuco_board = cv2.aruco.CharucoBoard((CELLS_X, CELLS_Y), CELL_WIDTH, MARKER_WIDTH, DICT)
charuco_board.setLegacyPattern(True)
#im = charuco_board.generateImage((CELLS_X * 100, CELLS_Y * 100))
#cv2.imshow("board", im)
#cv2.waitKey(0)

aruco_dict = DICT

all_corners = []
all_ids = []

all_detected_corners = []
all_detected_ids = []

images = glob.glob('/Users/anastasia/meowmeowX/cv/dataset 4/*.jpg')
img = cv2.imread('/Users/anastasia/meowmeowX/cv/frame_148.jpg')
#cv2.imshow('size', img)
#cv2.waitKey(1000)
#cv2.destroyAllWindows()
#print(img_files)
height, width, channels = img.shape

print(height/2)
print(width/2)

all_corners = []
all_ids = []
current = 0

for im in images:
    image = cv2.imread(im)
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    corners, ids, _ = cv2.aruco.detectMarkers(gray, aruco_dict)

    if ids is not None:
        ret, ch_corners, ch_ids = cv2.aruco.interpolateCornersCharuco(
            corners, ids, gray, charuco_board)
        if ret > 0:
            all_corners.append(ch_corners)
            all_ids.append(ch_ids)
            all_detected_corners.append(corners)
            all_detected_ids.append(ids)

# 相机标定
imsize = gray.shape
ret, camera_matrix, distortion_coefficients, _, _ = cv2.aruco.calibrateCameraCharuco(
    charucoCorners=all_corners,
    charucoIds=all_ids,
    board=charuco_board,
    imageSize=(imsize[1], imsize[0]),
    cameraMatrix=None,
    distCoeffs=None
)

print("camera matrix:\n", camera_matrix)
print("dis_coef:\n", distortion_coefficients)


540.0
960.0
camera matrix:
 [[1.75816631e+03 0.00000000e+00 9.95261535e+02]
 [0.00000000e+00 1.74374606e+03 5.86214872e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
dis_coef:
 [[ 1.50497653e-01 -1.14192203e+00 -8.38537659e-04 -1.96202401e-03
   1.08294422e+00]]
