In [10]:
import cv2
import numpy as np
import glob

DICT = cv2.aruco.DICT_6X6_50           # Тип маркеров aruco
CELLS_X, CELLS_Y = 5, 7             # Размер доски (количество клеток)
CELL_WIDTH, MARKER_WIDTH = 0.04, 0.02  # Размер клетки и маркера в метрах

DICT = cv2.aruco.getPredefinedDictionary(DICT)
charuco_board = cv2.aruco.CharucoBoard((CELLS_X, CELLS_Y), CELL_WIDTH, MARKER_WIDTH, DICT)

aruco_dict = DICT

all_corners = []
all_ids = []

all_detected_corners = []
all_detected_ids = []

images = glob.glob('dataset 0.0.0.1/*.jpg')
img = cv2.imread('Photo on 2023-11-12 at 14.37.jpg')
#cv2.imshow('size', img)
#cv2.waitKey(1000)
#cv2.destroyAllWindows()
#print(img_files)
height, width, channels = img.shape 

print(height/2)
print(width/2)

all_corners = []
all_ids = []
current = 0

for im in images:
    image = cv2.imread(im)
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    corners, ids, _ = cv2.aruco.detectMarkers(gray, aruco_dict)

    if ids is not None:
        ret, ch_corners, ch_ids = cv2.aruco.interpolateCornersCharuco(
            corners, ids, gray, charuco_board)
        if ret > 0:
            all_corners.append(ch_corners)
            all_ids.append(ch_ids)
            all_detected_corners.append(corners)
            all_detected_ids.append(ids)

if len(all_corners) > 0 and len(all_ids) > 0 and len(all_corners) == len(all_ids):
    ret, camera_matrix, distortion_coefficients, _, _ = cv2.aruco.calibrateCameraCharuco(
        charucoCorners=all_corners,
        charucoIds=all_ids,
        board=charuco_board,
        imageSize=(imsize[1], imsize[0]),
        cameraMatrix=None,
        distCoeffs=None
    )
else:
    print("Error: Not enough corner points or IDs for calibration")

# 相机标定
imsize = gray.shape
ret, camera_matrix, distortion_coefficients, _, _ = cv2.aruco.calibrateCameraCharuco(
    charucoCorners=all_corners,
    charucoIds=all_ids,
    board=charuco_board,
    imageSize=(imsize[1], imsize[0]),
    cameraMatrix=None,
    distCoeffs=None
)

print("camera matrix:\n", camera_matrix)
print("dis_coef:\n", distortion_coefficients)


840.0
1260.0
camera matrix:
 [[3.24364167e+03 0.00000000e+00 9.38618477e+02]
 [0.00000000e+00 3.22055936e+03 5.82990476e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
dis_coef:
 [[ 7.10199928e-01 -1.37853150e+01 -1.50329953e-03 -7.73077998e-03
   4.65342208e+01]]
